# Generated by Django 5.0.2 on 2024-03-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('role', models.SmallIntegerField(choices=[(1, 'Goalkeeper'), (2, 'Defender'), (3, 'Forward')])),
                ('gk_skill', models.SmallIntegerField(choices=[(1, '1 - Very bad'), (2, '2 - Bad'), (3, '3 - Medium'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('def_skill', models.SmallIntegerField(choices=[(1, '1 - Very bad'), (2, '2 - Bad'), (3, '3 - Medium'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('frw_skill', models.SmallIntegerField(choices=[(1, '1 - Very bad'), (2, '2 - Bad'), (3, '3 - Medium'), (4, '4 - Good'), (5, '5 - Excellent')])),
                ('is_in_roster', models.BooleanField(default=False)),
            ],
        ),
    ]
