# Generated by Django 5.0.2 on 2024-02-25 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        ('skills', '0002_remove_skilllevel_name_delete_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('def_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='def_skill', to='skills.skilllevel')),
                ('gk_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gk_skill', to='skills.skilllevel')),
                ('off_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='off_skill', to='skills.skilllevel')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role', to='roles.role')),
            ],
        ),
    ]
