# Generated by Django 5.0.2 on 2024-03-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='def_skill',
            field=models.SmallIntegerField(choices=[(1, '1 - Плохо'), (2, '2 - Ниже среднего'), (3, '3 - Нормально'), (4, '4 - Хорошо'), (5, '5 - Отлично')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='frw_skill',
            field=models.SmallIntegerField(choices=[(1, '1 - Плохо'), (2, '2 - Ниже среднего'), (3, '3 - Нормально'), (4, '4 - Хорошо'), (5, '5 - Отлично')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_skill',
            field=models.SmallIntegerField(choices=[(1, '1 - Плохо'), (2, '2 - Ниже среднего'), (3, '3 - Нормально'), (4, '4 - Хорошо'), (5, '5 - Отлично')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'Goalkeepers'), (2, 'Defenders'), (3, 'Forwards')]),
        ),
    ]
