# Generated by Django 5.0.2 on 2024-02-25 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_gk_skill_player_skill_remove_player_def_skill_and_more'),
        ('skills', '0002_remove_skilllevel_name_delete_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='skill',
            new_name='gk_skill',
        ),
        migrations.AddField(
            model_name='player',
            name='def_skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='def_skill', to='skills.skilllevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='off_skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='off_skill', to='skills.skilllevel'),
            preserve_default=False,
        ),
    ]
