# Generated by Django 5.0.2 on 2024-03-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_def_skill_alter_player_frw_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'Вратарь'), (2, 'Защитник'), (3, 'Нападающий')]),
        ),
    ]
