# Generated by Django 5.0.2 on 2024-03-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='def_skill',
            field=models.SmallIntegerField(choices=[(1, '1 - Very bad'), (2, '2 - Bad'), (3, '3 - Medium'), (4, '4 - Good'), (5, '5 - Excellent')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='frw_skill',
            field=models.SmallIntegerField(choices=[(1, '1 - Very bad'), (2, '2 - Bad'), (3, '3 - Medium'), (4, '4 - Good'), (5, '5 - Excellent')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='gk_skill',
            field=models.SmallIntegerField(choices=[(1, '1 - Very bad'), (2, '2 - Bad'), (3, '3 - Medium'), (4, '4 - Good'), (5, '5 - Excellent')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'Goalkeeper'), (2, 'Defender'), (3, 'Forward')]),
        ),
    ]
