# Generated by Django 5.0.2 on 2024-02-28 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0003_rename_skill_player_gk_skill_player_def_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
    ]
