# Generated by Django 5.0.2 on 2024-02-25 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilllevel',
            name='name',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
