# Generated by Django 5.0.2 on 2024-03-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_1_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2_goals',
            field=models.IntegerField(null=True),
        ),
    ]
