# Generated by Django 5.0.2 on 2024-03-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_team_1_goals_match_team_2_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
