# Generated by Django 5.0.2 on 2024-03-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_1_goals',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2_goals',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
