# Generated by Django 5.0.2 on 2024-03-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_match_team_1_goals_alter_match_team_2_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_1_goals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2_goals',
            field=models.IntegerField(),
        ),
    ]
