# Generated by Django 5.0.2 on 2024-03-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_match_team_1_goals_alter_match_team_2_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateField(),
        ),
    ]
