# Generated by Django 5.0.2 on 2024-03-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_alter_match_description_alter_match_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
